---
# Setup some gaming specific things

- name: Install Gaming Packages
  dnf:
    state: present
    name: '{{ install_gaming_packages}}'
  when:
    - enable_gaming == true

- name: Install Flatpak -> Discord
  flatpak:
    name:   com.discordapp.Discord
    state:  present
    remote: flathub
  when:
    - enable_gaming == true
  tags:
    - flatpak
    - packages


- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: gaming
  register: gaming_temp

- name: Clone Game Udev rules
  ansible.builtin.git:
    repo: https://gitlab.com/jntesteves/game-devices-udev.git
    dest: "{{ gaming_temp.path }}"

- name: Install gaming Udev rules
  ansible.builtin.copy:
    dest: /etc/ude/rules.d/
    src: "{{ gaming_temp.path }}/game-devices-udev/"

- name: enable uinput
  ansible.builtin.copy:
    dest: uinput.conf
    src: "/etc/modules-load.d/uinput.conf"
...