---
#Remove Packages
- name:         Remove Packages
  dnf:
    state:      absent
    name:       "{{ remove_packages }}"

# Install Packages
- name:         Install Packages
  dnf:
    state:      present
    name:       '{{ install_packages }}'
  #Keyboard Config. This will eventually be its own role.

- name:        Upgrade PIP
  pip:
    name:     pip
    state:    latest
    extra_args: --user

- name:       Install Required Python libraries
  become:     false
  pip:
    name:     "{{ python_packages }}"
    state:    latest
    extra_args: --user --upgrade

- name:         Install Extra Font Packages
  dnf:
    name:       "{{ extra_font_files }}"
    state:      present
  when:         install_extra_fonts
  notify:       Update Font Cache

# Install Citrix Packages
# - name:         Install Citrix Packages
#   dnf:
#     state:      present
#     name:       '{{ install_citrix_packages }}'
#   when:
#     - work == true
#     - citrix_receiver == true

# - name:         Install Citrix receiver
#   debug: "https://www.citrix.com/downloads/citrix-receiver/linux/receiver-for-linux-latest.html"
#   when:
#     - work == true
#     - citrix_receiver == true

- name:         Install CIFS Utils
  dnf:
    name:       cifs-utils
    state:      present
  when:
    - work == true
