# Remove Files
- name:       Remove unneeded packages
  dnf:
    state:    absent
    name:     "{{item}}"
  with_items:
    - thunderbird
  when:       (ansible_distribution == "Fedora" and ansible_distribution_major_version > "22")

# Install Files
- name:       Install needed packages
  dnf:
    state:    present
    name:     "{{item}}"
  with_items:
    - htop
    - wget
    - curl
    - nano
    - python-pip
    - nano
    - openssh
    - fwbackups
    - tmux
    - vlc
    - fslint
    - wget
    - p7zip
    - seahorse-nautilus
    - gnome-terminal-nautilus
  #Keyboard Config. This will eventually be its own role.
  when:       (ansible_distribution == "Fedora" and ansible_distribution_major_version > "22")
