# Remove Files
# - name:       Remove unneeded packages
#   dnf:
#     state:    absent
#     name:     "{{item}}"
#   with_items:
#     - thunderbird

# Install Files
- name:       Install needed packages
  dnf:
    state:    present
    name:     "{{install_package}}"
  with_items:
    - htop
    - wget
    - curl
    - nano
    - python-pip
    - nano
    - openssh
    - fwbackups
    - tmux
    - vlc
    - fslint
    - wget
    - p7zip
    - seahorse-nautilus
    - tilix
    - tilix-nautilus
  loop_control:
    loop_var: install_package
  #Keyboard Config. This will eventually be its own role.
