#!/usr/bin/env ansible-playbook
---
#Remove Packages
- name:         Remove Packages
  dnf:
    state:      absent
    name:       "{{ item }}"
  with_items:
    - gnome-shell-extension-background-logo
    - gnome-shell-extension-window-list

# Install Packages
- name:         Install Packages
  dnf:
    state:      present
    name:       "{{ install_package }}"
  with_items:
    - htop
    - wget
    - curl
    - nano
    - python-pip
    - nano
    - openssh
    - fwbackups
    - tmux
#    - vlc
#    - mpv
    - fslint
    - wget
    - p7zip
    - seahorse-nautilus
    - tilix
    - tilix-nautilus
    - chromium
    - chrome-gnome-shell
    - lm_sensors
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extension-calc
    - gnome-tweak-tool
    - gtk-murrine-engine
    - git
    - remmina
    - remmina-plugins-rdp
    - remmina-plugins-gnome
    - remmina-plugins-spice
    - remmina-plugins-vnc
    - util-linux-user
    - dnf-plugins-core
    - sqlite
    - python3
    - python3-pip
    - ImageMagick
    - tint2
    - mpv
    - python-firewall
    - parallel
  loop_control:
    loop_var:   install_package
  #Keyboard Config. This will eventually be its own role.

- name:         Install Extra Font Packages
  dnf:
    name:       "{{ item }}"
    state:      present
  with_items:
    - adobe-source-code-pro-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - levien-inconsolata-fonts
    - liberation-fonts-common
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - mozilla-fira-mono-fonts
    - msimonson-anonymouspro-fonts
    - overpass-fonts
    - terminus-fonts
  when:         install_extra_fonts
  notify:       Update Font Cache

- name: Unique custimzation tools
  pip:
    name: wpgtk
    executable: pip3
    extra_args: --user