#!/usr/bin/env ansible-playbook
---
#Remove Packages
- name:         Remove Packages
  dnf:
    state:      absent
    name:       "{{ item }}"
  with_items:
    - gnome-shell-extension-background-logo
    - gnome-shell-extension-window-list
    - tint2

# Install Packages
- name:         Install Packages
  dnf:
    state:      present
    name:       "{{ install_package }}"
  with_items:
    - htop
    - wget
    - curl
    - nano
    - python-pip
    - nano
    - openssh
    - fwbackups
    - tmux
#    - vlc
#    - mpv
    - fslint
    - wget
    - p7zip
    - seahorse-nautilus
    - tilix
    - tilix-nautilus
    - chromium
    - chrome-gnome-shell
    - lm_sensors
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extension-calc
    - gnome-tweak-tool
    - gtk-murrine-engine
    - remmina
    - remmina-plugins-rdp
    - remmina-plugins-spice
    - remmina-plugins-vnc
    - util-linux-user
    - dnf-plugins-core
    - sqlite
    - python3
    - python3-pip
    - ImageMagick
    # - python-firewall
    - parallel
    - brasero
    - dnf-automatic
    - jq
    - yubioath-desktop
  loop_control:
    loop_var:   install_package
  #Keyboard Config. This will eventually be its own role.

- name:         Install Extra Font Packages
  dnf:
    name:       "{{ item }}"
    state:      present
  with_items:
    - adobe-source-code-pro-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - levien-inconsolata-fonts
    - liberation-fonts-common
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - mozilla-fira-mono-fonts
    - msimonson-anonymouspro-fonts
    - overpass-fonts
    - terminus-fonts
    - google-android-emoji-fonts
    - google-noto-fonts-common
    - google-android-emoji-fonts
  when:         install_extra_fonts
  notify:       Update Font Cache

# - name:         Upgrade pip
#   pip:
#     name:       pip
# #    executable: /usr/bin/pip
#     extra_args: --user --upgrade

- name:         Check for slack
  stat:
    path:       /usr/bin/slack
  register:     slack_installed

# - debug:
#     msg:      "System {{ slack_installed }} "

- name:         Install Slack
  dnf:
    name:       "https://downloads.slack-edge.com/linux_releases/slack-2.8.0-0.1.fc21.x86_64.rpm"
    state:      present
  when:
    - install_slack == true
    - slack_installed.stat.exists == false

- name:         Remove Slack
  dnf:
    name:       "slack"
    state:      absent
  when:
    - install_slack == false
    - slack_installed.stat.exists == true