#!/usr/bin/env ansible-playbook
---
#Remove Packages
- name:         Remove Packages
  dnf:
    state:      absent
    name:       "{{ remove_packages }}"

# Install Packages
- name:         Install Packages
  dnf:
    state:      present
    name:       '{{ install_packages }}'
  #Keyboard Config. This will eventually be its own role.

- name:        Install Required Python libraries
  pip:
    name:     "{{ python_packages }}"
    state:    present

- name:         Install Extra Font Packages
  dnf:
    name:       "{{ extra_font_files }}"
    state:      present
  when:         install_extra_fonts
  notify:       Update Font Cache

- name:         Check for Slack
  stat:
    path:       /usr/bin/slack
  register:     slack_installed

- name:         Install Slack
  dnf:
    name:       "https://downloads.slack-edge.com/linux_releases/slack-2.8.0-0.1.fc21.x86_64.rpm"
    state:      present
  when:
    - install_slack == true
    - slack_installed.stat.exists == false

- name:         Remove Slack
  dnf:
    name:       "slack"
    state:      absent
  when:
    - install_slack == false
    - slack_installed.stat.exists == true


# Install Citrix Packages
- name:         Install Citrix Packages
  dnf:
    state:      present
    name:       '{{ install_citrix_packages }}'
  when:
    - work == true
    - citrix_receiver == true

# - name:         Install Citrix receiver
#   debug: "https://www.citrix.com/downloads/citrix-receiver/linux/receiver-for-linux-latest.html"
#   when:
#     - work == true
#     - citrix_receiver == true

- name:         Install CIFS Utils
  dnf:
    name:       cifs-utils
    state:      present
  when:
    - work == true
