#Remove Packages
- name:       Remove unneeded packages
  dnf:
    state:    absent
    name:     "{{item}}"
  with_items:
    - gnome-shell-extension-background-logo
    - gnome-shell-extension-window-list

# Install Packages
- name:       Install needed packages
  dnf:
    state:    present
    name:     "{{install_package}}"
  with_items:
    - htop
    - wget
    - curl
    - nano
    - python-pip
    - nano
    - openssh
    - fwbackups
    - tmux
#    - vlc
#    - mpv
    - fslint
    - wget
    - p7zip
    - seahorse-nautilus
    - tilix
    - tilix-nautilus
    - chromium
    - lm_sensors
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extension-calc
    - gnome-tweak-tool
    - git
  loop_control:
    loop_var: install_package
  #Keyboard Config. This will eventually be its own role.
