#!/usr/bin/env ansible-playbook
---

- name:          Check rpmFusion Non Free Repo
  stat:
    path:        /etc/yum.repos.d/rpmfusion-free.repo
  register:      rpmfusion_free

- name:          Download RPM Fusion free Repo
  get_url:
    url:         "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    mode:        0644
    dest:        "/tmp/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
  when:          rpmfusion_free.stat is not defined

- name:          Install RPM Fusion free Repo
  dnf:
    name:        "/tmp/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
    state:       present
  when:          rpmfusion_free.stat is not defined

- name:          Check rpmFusion Non Free Repo
  stat:
    path:        /etc/yum.repos.d/pmfusion-nonfree.repo
  register:      rpmfusion_nonfree

- name:          Download RPM Fusion nonfree Repo
  get_url:
    url:         "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    mode:        0644
    dest:        "/tmp/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
  when:          rpmfusion_nonfree.stat is not defined

- name:          Install RPM Fusion nonfree Repo
  dnf:
    name:        "/tmp/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
    state:       present
  when:          rpmfusion_nonfree.stat is not defined

- name:          Install virtualbox repo
  get_url:
    url:         "http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo"
    mode:        0644
    dest:        /etc/yum.repos.d/virtualbox.repo

- name:          Check negative17 Multimedia Repo
  stat:
    path:        /etc/yum.repos.d/fedora-multimedia.repo
  register:      fedora_multimedia

- name:          Download negative17 Multimedia Repo
  get_url:
    url:         "https://negativo17.org/repos/fedora-multimedia.repo"
    mode:        0644
    dest:        "/etc/yum.repos.d/fedora-multimedia.repo"
  when:          fedora_multimedia.stat is not defined

- name:          Check negative17 Steam Repo
  stat:
    path:        /etc/yum.repos.d/fedora-steam.repo
  register:      fedora_steam

- name:          Download negative17 Steam Repo
  get_url:
    url:         "https://negativo17.org/repos/fedora-steam.repo"
    mode:        0644
    dest:        "/etc/yum.repos.d/fedora-steam.repo"
  when:
    - fedora_steam.stat is not defined
    - install_steam == true

- name:          Check negative17 Nvidia Repo
  stat:
    path:        /etc/yum.repos.d/fedora-nvidia.repo
  register:      fedora_nvidia

- name:          Download negative17 Nvidia Repo
  get_url:
    url:         "https://negativo17.org/repos/fedora-nvidia.repo"
    mode:        0644
    dest:        "/etc/yum.repos.d/fedora-nvidia.repo"
  when:
    - fedora_nvidia.stat is not defined
    - install_nvidia == true

