- name:    Clear up DNF cache
  command: /usr/bin/dnf clean all
  when:    (ansible_distribution == "Fedora" and ansible_distribution_major_version > 22)

- name:    Download RPM Fusion Repos 1/2
  get_url:
    url:   http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{version}}.noarch.rpm
    mode:  0644
    dest:  /tmp/setup/rpmfusion-free-release-{{version}}.noarch.rpm

- name:    Download RPM Fusion Repos 2/2
  get_url:
    url:   http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{version}}.noarch.rpm
    mode:  0644
    dest:  /tmp/setup/rpmfusion-nonfree-release-{{version}}.noarch.rpm
  
- name:    Install RPM Fusion Repos 1/2
  dnf:
    name:  /tmp/setup/rpmfusion-free-release-{{version}}.noarch.rpm
    state: present
  
- name:    Install RPM Fusion Repos 2/2
  dnf:
    name:  /tmp/setup/rpmfusion-nonfree-release-{{version}}.noarch.rpm
    state: present
  
- name:    Install virtualbox repo
  get_url:
    url:   http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    mode:  0644
    dest:  /etc/yum.repos.d/virtualbox.repo
  



# rpm -ivh http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{version}}.noarch.rpm
