# ---
#Custom Shortcut for Tilix
# gsettings set org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0 name "Launch Tilix"
# gsettings set org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0 binding '<Primary><Alt>t'
# gsettings set org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0 command "tilix"

- name: Enable flathub repo
  command: "flatpak remote-add {{ item }}"
  register: flatpak_repo
  with_items:
    - "gnome https://sdk.gnome.org/gnome.flatpakrepo"
    - "flathub https://flathub.org/repo/flathub.flatpakrepo"
  changed_when: "'already exists' not in flatpak_repo.stderr"
  failed_when: "'already exists' not in flatpak_repo.stderr"

# Flatpacks to install. Need to figure out how to do this
# http://baedert.org/repo/org.baedert.corebird.flatpakref


# This will probably have to be adjusted for success
- name: Install flatpaks
  command: "flatpak install -y {{ item }}"
  register: flatpak_install
  with_items:
    - "flathub com.valvesoftware.Steam"
    - "http://baedert.org/repo/org.baedert.corebird.flatpakref"
  failed_when: "'already installed' not in flatpak_install.stderr"
  changed_when: "'already installed' not in flatpak_install.stderr"