# ---
#Custom Shortcut for Tilix
# gsettings set org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0 name "Launch Tilix"
# gsettings set org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0 binding '<Primary><Alt>t'
# gsettings set org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0 command "tilix"

- name: Enable flathub repo
  command: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

