---
# Install Debian Specific files.
- name:       Install needed  {{ ansible_os_family }} Specific packages
  apt:        state=present name={{item}}
  with_items:
    - firefox
    - redshift
    - gimp
    - gnome-boxes
    - filezilla
    - build-essential
    - libpam0g-dev
    - libcurl4-openssl-dev
    - xclip

#

- name:       Get GitKraken {{ ansible_os_family }}
  file:
    path:     "{{ dev_temp_path }}"
    state:    directory

- name:       Get GitKraken {{ ansible_os_family }}
  get_url:
    url:      https://release.gitkraken.com/linux/gitkraken-amd64.deb
    dest:     "{{ dev_temp_path }}/gitkraken-amd64.deb"
    mode:     0755

- name:       Install GitKraken {{ ansible_os_family }}
  apt:        deb="{{ dev_temp_path }}/gitkraken-amd64.deb"
