#!/usr/bin/env ansible-playbook
---

- name:           Running OS specific Configurations and Commands
  include:        "{{item}}"
  with_items:
  # - "{{ ansible_distribution }}/repos.yml"
  - "{{ ansible_distribution }}/system.yml"
  - "{{ ansible_distribution }}/packages.yml"


# - name:       Running generic Configurations and Commands
#   include:    "{{item}}"
#   with_items:
#     - "all_system.yml"
# Referencing the page I used to find out most of this https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html

- name:         Update pip
  pip:
    name:       pip
    state:      latest

- name:         Install python modules with pip
  become:       false
  pip:
    name:       "{{ pip_install }}"
    state:      latest
    extra_args: --user --upgrade
  with_items:
    - cfscrape
    - selenium
    - google-api-python-client
    - docker-py
    - docker
  loop_control:
    loop_var:   pip_install


- name: "Add {{ local_user }} to the docker group"
  user:
    name: "{{ local_user }}"
    groups: docker
    append: yes