---

- name:           Running OS specific Configurations and Commands
  include_tasks:  "{{ item }}"
  with_items:
  - "{{ ansible_distribution }}/packages.yml"
  - "{{ ansible_distribution }}/flatpak.yml"
  - "{{ ansible_distribution }}/system.yml"

- name:         Install python modules with pip
  become:       false
  pip:
    name:       "{{ pip_install }}"
    state:      latest
    extra_args: --user --upgrade


- name: "Add {{ local_user }} to the docker group"
  user:
    name: "{{ local_user }}"
    groups: docker
    append: yes
  when:               install_docker
