---


- name:           Running OS specific Configurations and Commands
  include:        "{{item}}"
  with_items:
  # - "{{ ansible_distribution }}/repos.yml"
  - "{{ ansible_distribution }}/system.yml"
  - "{{ ansible_distribution }}/packages.yml"


# - name:       Running generic Configurations and Commands
#   include:    "{{item}}"
#   with_items:
#     - "all_system.yml"
# Referencing the page I used to find out most of this https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html
