---
- name: Running OS specific Configurations and Commands
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    # - "{{ ansible_distribution }}/packages.yml"
    # - "{{ ansible_distribution }}/flatpak.yml"
    # - "{{ ansible_distribution }}/system.yml"
    - "{{ ansible_distribution }}/fonts.yml"

# - name: Install python modules with pip
#   become: false
#   ansible.builtin.pip:
#     name: "{{ pip_install }}"
#     state: latest
#     extra_args: --user --upgrade

- name: "Add to the docker group: {{ local_user }}"
  ansible.builtin.user:
    name: "{{ local_user }}"
    groups: docker
    append: true
  when: install_docker

...
