---

# Remove Files
- name: Remove unneeded packages
  dnf:
    state: absent
    name: "{{item}}"
  with_items:
    - nodejs
    - nodejs-devel
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version > "22")

# Install Files
- name: Install needed packages
  dnf:
    state: present
    name: "{{item}}"
  with_items:
    - filezilla
    - openssl-devel
    - xclip
    - vagrant
    - which
    - make
    - "@Development tools"
    - gcc-c++
    - levien-inconsolata-fonts
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - google-droid-sans-mono-fonts
    - python-devel
    - python
    - which
    - make
    - gtk-murrine-engine
    # PHP specific files
    - php-mbstring
    - php-pdo
    - php-mysqlnd
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version > "22")
