  - name: Allow Access to SNMP Debian
    lineinfile:
      dest: "/etc/snmp/snmpd.conf"
      regexp: "^agentAddress udp:127.0.0.1:161"
      line: "agentAddress 161"
      state: present
    notify: restart snmp

  - name: Allow public to access Debian
    lineinfile:
      dest: "/etc/snmp/snmpd.conf"
      regexp: "^#rocommunity public localhost"
      line: "rocommunity public "
      state: present
    notify: restart snmp
