---
# - hosts:          localhost
#   become:         false
#   connection:     local
#   roles:
#     - vaulttec.zsh
#   vars_files:
#     - vars/main.yml
#     - vars/zsh.yml
#     - vars/vault.yml

- hosts:          localhost
  become:         true
  connection:     local
  pre_tasks:
    - name:       Install Manditory base files
      package:
        state:    present
        name:     "{{ item }}"
      with_items:
        - libselinux-python
  roles:
    - base
    - developer
    # - geerlingguy.docker
    # - docker-syncthing
    # - vs-code
    # - arduino
    - geerlingguy.git
    - geerlingguy.pip
    - geerlingguy.php
    - geerlingguy.composer
    # - VirtualBox
    # - geerlingguy.ansible
  vars_files:
    - vars/main.yml
    - vars/vault.yml


...