---

- hosts:          localhost
  become:         true
  connection:     local
  pre_tasks:
    # - name:       Install Manditory base files
    #   package:
    #     state:    present
    #     name:     "{{ item }}"
    #   with_items:
    #     - python3-libselinux
  roles:
    - base
    - developer
    # - geerlingguy.docker
    - vs-code
    - vaulttec.zsh
    # - arduino
    # - geerlingguy.git
    # - geerlingguy.pip
    # - geerlingguy.php
    # - geerlingguy.composer
    # - geerlingguy.ansible
  vars_files:
    - vars/main.yml
    - vars/zsh.yml
    # - vars/vault.yml


...