---
- hosts:          localhost
  become:         true
  connection:     local
  pre_tasks:
    - name:       Install Manditory base files
      package:
        state:    present
        name:     "{{ item }}"
      with_items:
        - libselinux-python
  roles:
    - vaulttec.zsh
    - base
    - developer
    # - arduino
    # - geerlingguy.git
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.php
    - vs-code
    - geerlingguy.composer
    # - VirtualBox
    # - geerlingguy.ansible
    # - docker-syncthing

  vars_files:
    - vars/main.yml
    - vars/vault.yml
