---
- hosts: localhost
  become: true
  connection: local
  pre_tasks:
  roles:
    # - geerlingguy.ansible
    # - vs-code
    # - geerlingguy.git
    # - base
    # - vaulttec.zsh
    # - geerlingguy.pip
    # - geerlingguy.php
    # - geerlingguy.composer
    - role: developer
      when: enable_developer_mode is true
    - role: laptop
      when: laptop is true
  vars_files:
    - vars/vault
    - vars/main.yml
    - vars/zsh.yml
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  vars_prompt:
    - name: laptop
      prompt: Is this a laptop?
      private: no
      default: false
    - name: local_user
      prompt: What is your local user account?
      private: no
      default: joe
    - name: enable_gaming
      prompt: Should I enable gaming?
      private: no
      default: False
    - name: enable_developer_mode
      prompt: Should I enable Developer Mode??
      private: no
      default: False
