---
- hosts: localhost
  become: true
  connection: local
  roles:
    # - geerlingguy.ansible
    # - geerlingguy.git
    - base
    - gnome
    - flatpak
    # - vaulttec.zsh
    # - geerlingguy.pip
    # - geerlingguy.php
    # - geerlingguy.composer
    # - vs-code
    - role: developer
      when: enable_developer_mode is true
    - role: laptop
      when: enable_laptop_mode is true
    - role: yubikey
      when: yubikey_enable is true
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml
    - vars/zsh.yml
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  vars_prompt:
    # - name: enable_laptop_mode
    #   prompt: Is this a laptop?
    #   private: no
    #   default: false
    # - name: local_user
    #   prompt: What is your local user account?
    #   private: no
    #   default: joe
    # - name: enable_gaming
    #   prompt: Should I enable gaming?
    #   private: no
    #   default: false
  #   - name: enable_developer_mode
  #     prompt: Should I enable Developer Mode??
  #     private: no
  #     default: false
    # - name: yubikey
    #   prompt: Please enter yubikey
    #   private: true

    # - name: yubikey_ssh_login
    #   prompt: Enable login to SSH
    #   private: no
    #   default: false
