---
- hosts:          localhost
  become:         true
  connection:     local
  pre_tasks:
    - name:       Install Manditory base files
      dnf:
        state:    present
        name:     "{{ item }}"
      with_items:
        - libselinux-python
  roles:
    - base
    - developer
    # - zsh
    # - vs-code
    # - mjanser.firewalld
    # - geerlingguy.php
    # - geerlingguy.composer
    # - ansible-role-docker
    # - docker-syncthing

  vars_files:
    - vars/main.yml
    - vars/vault.yml