---
- hosts:          localhost
  become:         true
  connection:     local
  pre_tasks:
    - name:       Install Manditory base files
      dnf:
        state:    present
        name:     "{{ item }}"
      with_items:
        - libselinux-python
  roles:
    - base
    # - developer
    - arduino
    - geerlingguy.git
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.php
    # - abez.zsh
    - vs-code
    # - geerlingguy.composer
    # - mjanser.firewalld
    # - mjanser.firewalld
    # - VirtualBox
    # - geerlingguy.ansible

    # - docker-syncthing

  vars_files:
    - vars/main.yml
    - vars/vault.yml
