---
- hosts: localhost
  become: true
  connection: local
  pre_tasks:
  roles:
    - geerlingguy.ansible
    - vs-code
    - geerlingguy.git
    - base
    # - developer
    - vaulttec.zsh
    # - geerlingguy.pip
    # - geerlingguy.php
    # - geerlingguy.composer
  vars_files:
    - vars/vault
    - vars/main.yml
    - vars/zsh.yml
  vars:
    - ansible_python_interpreter: /usr/bin/python3