---
- hosts: localhost
  become: true
  connection: local
  roles:
    - silverblue
    - flatpak
    - role: yubikey
      when: yubikey_enable is true
  vars_files:
    - vars/main.vault.yml
    - vars/main.yml
    - vars/zsh.yml
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  vars_prompt: []