---

- src: geerlingguy.php
  version: 4.2.0
- src: geerlingguy.git
  version: 3.0.0
- src: geerlingguy.pip
  version: 1.3.0
- src: geerlingguy.composer
  version: 1.7.6
- src: geerlingguy.ansible
  version: 2.0.2
- src: geerlingguy.docker
  version: 2.7.0
- src: mjanser.firewalld
  version: v1.4
- src: vaulttec.zsh
  version: master
- src: artis3n.tailscale
  version: v1.13.3
- src: robertdebock.rpmfusion
  version: 1.3.3