#!/usr/bin/env ansible-playbook
---
- name:       Install Nvidia Cuda
  dnf:
    name:     "{{ nvidia_packages }}"
    state:    present
  when:
    - install_nvidia == true
    - install_cuda == true

- name:         Install Packages
  dnf:
    state:      present
    name:       '{{ install_packages }}'