nagios-plugins:
    - nagios-nrpe
    - nagios-plugins-swap
    - nagios-plugins-users
    - nagios-plugins-procs
    - nagios-plugins-load
    - nagios-plugins-disk
    - nagios-plugins-standard
    - nagios-plugins-contri
