---
# tasks file for docker-syncthing

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add local user to Docker group
  user:
    name: "{{ local_user }}"
    groups: docker
    append: yes


- name: Create Docker paths System
  file:
    path: "{{ docker_syncthing_storage }}/{{ item }}"
    state: directory
    owner: "{{ local_user }}"
    group: docker
    mode: 0775
  with_items:
    - config
    - data

- name: Create Docker paths Home
  file:
    path: "/home/{{ local_user }}/{{ item }}"
    state: directory
    owner: "{{ local_user }}"
    group: docker
    mode: 0775
  with_items:
    - Pictures
    - tapet
    - syncthing
    - camera

- name: Create Syncthing container
  docker_container:
    name: syncthing
    image: linuxserver/syncthing
    state: started
    restart_policy: unless-stopped
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - 8384
      - 22000
      - 21027/udp
    published_ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - "{{ docker_syncthing_storage }}/data/:/mnt/data/"
      - "{{ docker_syncthing_storage }}/config:/config"
      - "/home/{{ local_user }}/Pictures:/mnt/pictures"
      - "/home/{{ local_user }}/tapet:/mnt/tapet"
      - "/home/{{ local_user }}/syncthing:/mnt/joe"
      - "/home/{{ local_user }}/camera:/mnt/camera"
      - "/home/{{ local_user }}/Documents:/mnt/documents"
    env:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1001

- lineinfile:
    path: "{{ docker_syncthing_storage }}/config/config.xml"
    regexp: '^<apikey>'
    line: "<apikey>{{ syncthing_api_key }}</apikey>"
    backup: true
    backrefs: true
  register: reloadContainer

- name: Open Ports for Syncthing
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
