---
# tasks file for docker-syncthing

- name: Create Docker paths
  file:
    path: "{{ docker_syncthing_storage }}/{{ item }}"
    state: directory
    owner: "{{ local_user }}"
    group: docker
    mode: 0775
  with_items:
    - config
    - data

- name: Create Docker paths
  file:
    path: "/mnt/syncthing/{{ local_user }}/{{ item }}"
    state: directory
    owner: "{{ local_user }}"
    group: docker
    mode: 0775
  with_items:
    - pictures
    - tapet
    - camera
    - documents
    - personal

- name: Create Syncthing container
  become: False
  docker_container:
    name: syncthing
    image:  linuxserver/syncthing
    state: started
    restart_policy: unless-stopped
    hostname: d-it01-syncthing
    recreate: yes
    restart: yes
    pull: true
    exposed_ports:
      - 8384
      - 22000
      - 21027/udp
    published_ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - "{{ docker_syncthing_storage }}/data/:/mnt/data/"
      - "{{ docker_syncthing_storage }}/config:/config"
      - "/mnt/syncthing/{{ local_user }}/pictures:/mnt/pictures"
      - "/mnt/syncthing/{{ local_user }}/tapet:/mnt/tapet"
      - "/mnt/syncthing/{{ local_user }}/personal:/mnt/joe "
      - "/mnt/syncthing/{{ local_user }}/camera:/mnt/camera"
      - "/mnt/syncthing/{{ local_user }}/documents:/mnt/documents"
    env:
      TZ: America/Chicago
      PUID: 1000
      PGID: 1001


- name: Open Ports for Syncthing
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - "{{ docker_ports }}"
  notify: Restart firewalld
