---
- name:           "Running {{ansible_os_family}} - {{ ansible_distribution }} specific Configurations and Commands"
  include_tasks:        "{{ ansible_os_family }}.yml"
  tags:
    - code
    - configuration
- name:         Install Extensions
  become:       no
  command:      "/usr/bin/code --install-extension '{{ extension }}'"
  with_items:
    - "{{ vscode_extensions }}"
  register:     vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
  loop_control:
    loop_var:   extension
  tags:
    - code
    - configuration
...