---
# Themes are in a dir/theme format
# Directories are either Themes or Themes-2

# dotfiles_repo_RO: https://github.com/Findarato/dotFiles.git
dotfiles_repo_RW: git@github.com:Findarato/dotFiles.git

install_packages:
  - alacritty
  - aria2
  - cargo
  - chrome-gnome-shell
  - chromium-freeworld
  - curl
  - dnf-automatic
  - dnf-plugins-core
  - exa
  - flameshot
  - gnome-shell-extension-auto-move-windows
  - gnome-shell-extension-user-theme
  - gnome-tweak-tool
  - gtk-murrine-engine
  - htop
  - httpie
  - ImageMagick
  - jq
  - lm_sensors
  - mpv
  - nano
  - openssh
  - p7zip
  - parallel
  - perl-LWP-Protocol-https
  - pidgin
  - pidgin-hangouts
  - podman
  - prettyping
  - purple-hangouts
  - remmina
  - remmina-plugins-rdp
  - remmina-plugins-spice
  - remmina-plugins-vnc
  - restic
  - sqlite
  - stow
  - tilix
  - tilix-nautilus
  - tmux
  - util-linux-user
  - variety

i3_packages:
  - automake
  - compton
  - dunst
  - feh
  - i3-gaps
  - i3lock-color
  - lxappearance
  - rofi
  - rofi
  - rofi-themes
  - sysstat

remove_packages:
  - chromium
  - flowblade
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gtkhash-nautilus
  - tint2
  - totem
  - virtualbox-guest-additions

extra_font_files:
  - adobe-source-code-pro-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - google-android-emoji-fonts
  - google-android-emoji-fonts
  - google-noto-fonts-common
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts

nvidia_packages:
  - cuda
  - cuda-cudart
  - nvidia-driver-cuda

flatpak_packages:
  - https://flathub.org/repo/appstream/com.axosoft.GitKraken.flatpakref
  - org.gnome.Lollypop
  - io.dbeaver.DBeaverCommunity

python_packages:
  - redis
  - tuir

rpmfusion_free_package_state: present
rpmfusion_nonfree_package_state: present

dconf_settings_theme: []

dconf_usability_improvements: []

automounts: []

tilix_themes:
  - "Themes/espresso.json"
  - "Themes/espresso-libre.json"

...
