---
# This is giving me issues
- name: Add the flathub flatpak repository remote to the user installation
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: absent

- name: Add the flathub flatpak repository remote to the user installation
  become: true
  become_user: "{{ local_user }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Add the gnome nightly flatpak repository remote to the user installation
  become: true
  become_user: "{{ local_user }}"
  community.general.flatpak_remote:
    name: gnome-nightly
    state: present
    method: user
    flatpakrepo_url: https://nightly.gnome.org/gnome-nightly.flatpakrepo

- name: 📦 Install Flathub Flatpak Packages
  become: true
  become_user: "{{ local_user }}"
  community.general.flatpak:
    name: "{{ flatpak_install }}"
    state: present
    remote: flathub
    method: user
  with_items:
    - "{{ flatpak_packages_flathub }}"
  loop_control:
    loop_var: flatpak_install
  tags:
    - flatpak
    - packages

- name: 📦 Home Install Flathub Flatpak Packages
  become: true
  become_user: "{{ local_user }}"
  community.general.flatpak:
    name: "{{ flatpak_install_home }}"
    state: present
    remote: flathub
    method: user
  with_items:
    - "{{ flatpak_packages_flathub_home }}"
  loop_control:
    loop_var: flatpak_install_home
  when:
    - work_computer is false
  tags:
    - flatpak
    - packages

- name: 📦 Install gnome nightly Flatpak Packages
  become: true
  become_user: "{{ local_user }}"
  community.general.flatpak:
    name: "{{ flatpak_install }}"
    state: present
    remote: gnome-nightly
    method: user
  with_items:
    - "{{ flatpak_packages_gnome_nightly }}"
  loop_control:
    loop_var: flatpak_install
  tags:
    - flatpak
    - packages

- name: 📦 Copy auto update files
  copy:
    src: etc/
    dest: /etc

- name: 📦 Enable User Auto update timers
  ansible.builtin.systemd:
    name: update-user-flatpaks.timer
    daemon_reload: true
    enabled: true
    state: started
    scope: user

- name: 📦 Enable System Auto update timers
  ansible.builtin.systemd:
    name: update-system-flatpaks.timer
    daemon_reload: true
    enabled: true
    state: started

