---
- name:       📦 Install Flatpak
  package:
    name:     flatpak
    state:    present
  become:     True


# This is giving me issues
- name: Add the flathub flatpak repository remote to the user installation
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Add the gnome nightly flatpak repository remote to the user installation
  become: true
  community.general.flatpak_remote:
    name: gnome-nightly
    state: present
    method: user
    flatpakrepo_url: https://nightly.gnome.org/gnome-nightly.flatpakrepo


- name: 📦 Install Flathub Flatpak Packages
  community.general.flatpak:
    name:   "{{ flatpak_install }}"
    state:  present
    remote: flathub
    method: user
  with_items:
    - "{{ flatpak_packages_flathub }}"
  loop_control:
    loop_var:         flatpak_install
  tags:
    - flatpak
    - packages

- name: 📦 Install gnome nightly Flatpak Packages
  community.general.flatpak:
    name:   "{{ flatpak_install }}"
    state:  present
    remote: gnome-nightly
    method: user
  with_items:
    - "{{ flatpak_packages_gnome_nightly }}"
  loop_control:
    loop_var:         flatpak_install
  tags:
    - flatpak
    - packages

- name: 📦 Install Flatpak -> Bitwarden
  community.general.flatpak:
    name:   com.bitwarden.desktop
    state:  present
    remote: flathub
  tags:
    - flatpak
    - packages
  when:
    - install_bitwarden is true
...