---
# Add user to the correct group
# usermod -aG dialout public
- name: Setup group permissions for arduino access
  group: name={{item}} state=present
  with_items:
    - dialout
    - tty

# Add the user to the groups listed above
- name: Add users to correct Groups
  user: name={{item}} shell=/bin/bash groups=dialout,tty append=yes generate_ssh_key=yes ssh_key_file=.ssh/ansible
  with_items: {{arduino_users}}
