---
# Run the equivalent of "apt-get update" as a separate step
- name: Installing required Arduino files
  apt: update_cache=yes name={{item}}
  with_items:
  - arduino
  - arduino-core

- include: permissions.yml
