---
- name: Running OS specific Configurations and Commands
  ansible.builtin.include_tasks: "{{ include_file }}"
  with_items:
    - "repos.yml"
    - "packages.yml"
  loop_control:
    loop_var: include_file
  tags:
    - configuration

- name: Run system76 configuration
  ansible.builtin.include_tasks: system76.yml
  when:
    - "ansible_board_vendor  ==  System76"
  tags:
    - configuration
    - system76
