---
- name: Clear up DNF cache
  command: /usr/bin/dnf clean all
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version > 22)

- name: Add multiple repositories into the same file 1
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "6")

- name: Add multiple repositories into the same file 2
  yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
    enabled: no
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version > "6")

- name: Add Purple Hangouts COPR Repo
  command: /usr/bin/dnf copr endable xvitaly/purple-hangouts creates=/etc/yum.repos.d/_copr_xvitaly-purple-hangouts.repo
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version > "22")
