---
# Install Flatpak to ensure that it works
- name:       Install 'flatpak'
  package:
    name:     flatpak
    state:    present
  become:     yes


# This is giving me issues
- name: Add the flathub flatpak repository remote to the user installation
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak -> Slack
  flatpak:
    name:   com.slack.Slack
    state:  present
    remote: flathub
  tags:
    - flatpak
    - packages
  when:
    - install_slack is true

...