---

- name:         State of System
  stat:
    path:       /usr/share/fonts/mozilla-fira/FiraMono-Bold.otf
  register:     mozillaFiraMonoBold

# Remove Files
- name:         Remove unneeded packages
  dnf:
    state:      absent
    name:       "{{ remove_packages }}"
  when:         mozillaFiraMonoBold.stat.exists == False

# Install Files
- name:         Install needed packages
  dnf:
    state:      present
    name:       "{{ add_packages }}"
  notify:       Update Font Cache

