#!/usr/bin/env ansible-playbook
---

- name:         State of System
  stat:
    path:       /usr/share/fonts/mozilla-fira/FiraMono-Bold.otf
  register:     mozillaFiraMonoBold

# Remove Files
- name:         Remove unneeded packages
  dnf:
    state:      absent
    name:       "{{ remove_package }}"
  with_items:
    - nodejs
    - nodejs-devel
    - docker
    - docker-common
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
  loop_control:
    loop_var:   remove_package
  when:         mozillaFiraMonoBold.stat.exists == False

# Install Files
- name:         Install needed packages
  dnf:
    state:      present
    name:       "{{ install_package }}"
  with_items:
    - filezilla
    - openssl-devel
    - xclip
    - vagrant
    - which
    - make
    - gcc-c++
    - levien-inconsolata-fonts
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - google-droid-sans-mono-fonts
    - python-devel
    - python
    - which
    - make
    # PHP specific files
    - php-mbstring
    - php-pdo
    - php-mysqlnd
    - python-requests
    - nodejs
    - inkscape
    - sassc
    - libsass
    - glib2-devel
    - bison
    - flex
  loop_control:
    loop_var:   install_package
  notify:       Update Font Cache

- name:         Update pip
  pip:
    name:       pip
    state:      latest

- name:         Install python modules with pip
  become:       false
  pip:
    name:       "{{ pip_install }}"
    state:      latest
    extra_args: --user --upgrade
  with_items:
    - cfscrape
    - selenium
    - google-api-python-client
  loop_control:
    loop_var:   pip_install