#!/usr/bin/env ansible-playbook
---

# Remove Files
- name:       Remove unneeded packages
  dnf:
    state:    absent
    name:     "{{remove_package}}"
  with_items:
    - nodejs
    - nodejs-devel
  loop_control:
    loop_var: remove_package

# Install Files
- name:       Install needed packages
  dnf:
    state:    present
    name:     "{{install_package}}"
  with_items:
    - filezilla
    - openssl-devel
    - xclip
    - vagrant
    - which
    - make

    - gcc-c++
    - levien-inconsolata-fonts
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - google-droid-sans-mono-fonts
    - python-devel
    - python
    - which
    - make
    - gtk-murrine-engine
    # PHP specific files
    - php-mbstring
    - php-pdo
    - php-mysqlnd
  loop_control:
    loop_var: install_package