#!/usr/bin/env ansible-playbook
---

# Remove Files
- name:       Remove unneeded packages
  dnf:
    state:    absent
    name:     "{{remove_package}}"
  with_items:
    - nodejs
    - nodejs-devel
    - docker
    - docker-common
    - docker-selinux
    - docker-engine-selinux
    - docker-engine
  loop_control:
    loop_var: remove_package

# Install Files
- name:       Install needed packages
  dnf:
    state:    present
    name:     "{{install_package}}"
  with_items:
    - filezilla
    - openssl-devel
    - xclip
    - vagrant
    - which
    - make
    - gcc-c++
    - levien-inconsolata-fonts
    - adobe-source-code-pro-fonts
    - mozilla-fira-mono-fonts
    - google-droid-sans-mono-fonts
    - python-devel
    - python
    - which
    - make
    - gtk-murrine-engine
    # PHP specific files
    - php-mbstring
    - php-pdo
    - php-mysqlnd
    - python-requests
    - nodejs
#Docker Related Files

  loop_control:
    loop_var: install_package

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Install python modules with pip
  pip:
    name: cfscrape
    state: present
