---

- name:         Font => Create FiraCode Directory
  file:
    path:       /usr/share/fonts/FiraCode/
    state:      directory
    mode:       0755

- name:         Font => Install FiraCode
  unarchive:
    src:        "https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip"
    dest:       /usr/share/fonts/FiraCode/
    creates:    /usr/share/fonts/FiraCode/fira_code.css
    remote_src: yes
  notify:       Update Font Cache

- name:         Font => Create Hack Directory
  file:
    path:       /usr/share/fonts/Hack/
    state:      directory
    mode:       0755

- name:         Font => Install Hack
  unarchive:
    src:        "https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip"
    dest:       /usr/share/fonts/Hack/
    creates:    /usr/share/fonts/Hack/Hack-Bold.ttf
    remote_src: yes
  notify:       Update Font Cache

- name:         Font => Create Overpass Directory
  file:
    path:       /usr/share/fonts/Overpass/
    state:      directory
    mode:       0755

- name:         Font => Install Overpass
  unarchive:
    src:        "https://github.com/RedHatOfficial/Overpass/releases/download/v3.0.5/overpass-3.0.5.zip"
    dest:       "/usr/share/fonts/Overpass/"
    creates:    "/usr/share/fonts/Overpass/overpass/overpass-bold.otf"
    remote_src: yes
  notify:       Update Font Cache