---
#Remove Packages
- name:         Remove Packages
  dnf:
    state:      absent
    name:       "{{ remove_packages }}"

# Install Packages
- name:         Install Packages
  dnf:
    state:      present
    name:       '{{ install_packages }}'
  #Keyboard Config. This will eventually be its own role.

- name:        Upgrade PIP
  pip:
    name:     pip
    state:    latest
    extra_args: --user

- name:       Install Required Python libraries
  become:     false
  pip:
    name:     "{{ python_packages }}"
    state:    latest
    extra_args: --user --upgrade

- name:         Install Extra Font Packages
  dnf:
    name:       "{{ extra_font_files }}"
    state:      present
  when:         install_extra_fonts
  notify:       Update Font Cache


- name:         Install Bibata Cursors
  dnf:
    name:       bibata-cursor-themes
    state:      present
  ignore_errors: true

#https://github.com/ful1e5/Bibata_Cursor/releases/latest
#https://github.com/ful1e5/Bibata_Cursor/releases/download/latest/Bibata-Modern-Ice.tar.gz