---
  - name: Add multiple repositories into the same file 1
    yum_repository:
      name: epel
      description: EPEL YUM repo
      file: external_repos
      baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      gpgcheck: no

  - name: Add multiple repositories into the same file 2
    yum_repository:
      name: rpmforge
      description: RPMforge YUM repo
      file: external_repos
      baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
      mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
      enabled: no
