---
  
- name: Clear up DNF cache
  command: /usr/bin/dnf clean all
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version > 22)

- name: Add Purple Hangouts COPR Repo
  get_url: url=https://copr.fedorainfracloud.org/coprs/xvitaly/purple-hangouts/repo/fedora-24/xvitaly-purple-hangouts-fedora-24.repo dest=/etc/yum.repos.d/xvitaly-purple-hangouts-fedora-24.repo mode=0644
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version == "24")

- name: Install RPM Fusion Repos 1/2
  dnf:  name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-24.noarch.rpm state=present
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version == "24")

- name: Install RPM Fusion Repos 2/2
  dnf:  name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-24.noarch.rpm state=present
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version == "24")




# rpm -ivh http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-24.noarch.rpm
