---
### TODO: look into running this against silverblue

- name: Running OS specific Configurations and Commands
  include_tasks: "{{item}}"
  with_items:
  - "{{ ansible_os_family }}_packages.yml"
#  - "{{ ansible_os_family }}_system.yml"


- name: Install Udev rules from ublue
  become: true
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: /etc/udev/rules.d/
    loop:
      - https://raw.githubusercontent.com/ublue-os/config/main/files/etc/udev/rules.d/70-u2f.rules
  notify: Restart Udev


- name: Install Packages
  package:
    state: installed
    name: ["pam_yubico"]

...