#!/usr/bin/env ansible-playbook
---
# Themes are in a dir/theme format
# Directories are either Themes or Themes-2

dotfiles_repo_RO: https://github.com/Findarato/dotFiles.git
dotfiles_repo_RW: git@github.com:Findarato/dotFiles.git

install_packages:
  # - python-firewall
  - ImageMagick
  - brasero
  - chrome-gnome-shell
  - chromium
  - curl
  - dnf-automatic
  - dnf-plugins-core
  - fslint
  - fwbackups
  - gnome-shell-extension-calc
  - gnome-shell-extension-topicons-plus
  - gnome-tweak-tool
  - gtk-murrine-engine
  - htop
  - jq
  - lm_sensors
  - mpv
  - nano
  - openssh
  - p7zip
  - parallel
  - prettyping
  - python-pip
  - python3
  - python3-pip
  - remmina
  - remmina-plugins-rdp
  - remmina-plugins-spice
  - remmina-plugins-vnc
  - seahorse-nautilus
  - sqlite
  - tilix
  - tilix-nautilus
  - tmux
  - util-linux-user
  - vlc
  - wget
  # - yubioath-desktop

install_citrix_packages:
  - heimdal-libs
  - libidn1.34

remove_packages:
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-window-list
  - tint2

extra_font_files:
  - adobe-source-code-pro-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - google-android-emoji-fonts
  - google-android-emoji-fonts
  - google-noto-fonts-common
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts

nvidia_packages:
  - cuda
  - cuda-cudart
  - nvidia-driver-cuda

flatpak_packages:
  - https://flathub.org/repo/appstream/com.axosoft.GitKraken.flatpakref
  - com.github.alecaddd.sequeler

python_packages:
  - psutil
  - redis
...