---
# Themes are in a dir/theme format
# Directories are either Themes or Themes-2

# dotfiles_repo_RO: https://github.com/Findarato/dotFiles.git
dotfiles_repo_RW: git@github.com:Findarato/dotFiles.git

install_packages:
  - aria2
  - chrome-gnome-shell
  - curl
  - dnf-automatic
  - dnf-plugins-core
  - flameshot
  - gnome-shell-extension-auto-move-windows
  - gnome-shell-extension-user-theme
  - gnome-tweak-tool
  - gtk-murrine-engine
  - htop
  - httpie
  - ImageMagick
  - jq
  - lm_sensors
  - mpv
  - nano
  - openssh
  - p7zip
  - parallel
  - perl-LWP-Protocol-https
  - pidgin
  - pidgin-hangouts
  - podman
  - prettyping
  - purple-hangouts
  - remmina
  - remmina-plugins-rdp
  - remmina-plugins-spice
  - remmina-plugins-vnc
  - sqlite
  - tilix
  - tilix-nautilus
  - tmux
  - util-linux-user
  - variety
  - stow
  - p7zip
  - restic

i3_packages:
  - i3-gaps
  - rofi
  # -  'i3lock-color
  - i3lock
  - dunst
  - compton
  - feh
  - lxappearance
  - sysstat
  - rofi
  - rofi-themes
  - automake

install_citrix_packages:
  # - heimdal-libs
  # - libidn1.34

remove_packages:
  - chromium
  - flowblade
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-shell-extension-dash-to-dock
  - gtkhash-nautilus
  - tint2
  - totem


extra_font_files:
  - adobe-source-code-pro-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - google-android-emoji-fonts
  - google-android-emoji-fonts
  - google-noto-fonts-common
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts

nvidia_packages:
  - cuda
  - cuda-cudart
  - nvidia-driver-cuda

flatpak_packages:
  - https://flathub.org/repo/appstream/com.axosoft.GitKraken.flatpakref
  - org.gnome.Lollypop
  - io.dbeaver.DBeaverCommunity

python_packages:
  - redis
  - tuir


dconf_settings_theme:
  - name: Icon Theme
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Papirus-Dark'"
  - name: GTK Theme
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Arc-Dark'"
  - name: Shell Theme
    key: "/org/gnome/desktop/interface/user-theme"
    value: "'Arc-Dark-solid'"

#Needs a rework

# dconf_dash_to_dock_theme:
#   - name: No Custom Theme
#     key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme"
#     value: 0
#   - name: Remove Background Color
#     key: "/org/gnome/shell/extensions/dash-to-dock/custom-background-color"
#     value: 0
#   - name: Turn on Running Dots
#     key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-customize-running-dots"
#     value: 1
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-color"
#     value: "'#729fcf'"
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink"
#     value: 1
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
#     value: 0
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
#     value: 1
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/force-straight-corner"
#     value: 0
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/icon-size-fixed"
#     value: 1
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/intellihide-mode"
#     value: "'ALL_WINDOWS'"
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces"
#     value: 1
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/show-apps-at-top"
#     value: 1
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/unity-backlit-items"
#     value: 0
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/transparency-mode"
#     value: "'FIXED'"
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/running-indicator-style"
#     value: "'SEGMENTED'"
#   - name:
#     key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity"
#     value: 0.85


dconf_usability_improvements:
  - name: Make the mouse better
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'adaptive'"
  - name:
    key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value:  1
  - name: Show Weekdate
    key: "/org/gnome/desktop/calendar/show-weekdate"
    value:  1
  - name:
    key: "/org/gnome/desktop/wm/preferences/resize-with-right-button"
    value:  1
  - name: Fix Buttons
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"
  - name: Workspaces on all monitors
    key: "/org/gnome/shell.o/errides/workspaces-only-on-primary"
    value: 0

tilix_themes:
  - "Themes/espresso.json"
  - "Themes/espresso-libre.json"
...
