install_gaming_packages:
  - goverlay
  - mangohud

install_packages:
  - alacritty
  - aria2
  - autojump-zsh
  - bitstream-vera-fonts-all
  - cargo
  - chromium-freeworld
  - curl
  - dnf-automatic
  - dnf-plugins-core
  - exa
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-auto-move-windows
  - gnome-shell-extension-dash-to-dock
  - gnome-tweak-tool
  - htop
  - ImageMagick
  - jq
  - kitty
  - lm_sensors
  - nano
  - openssh
  - p7zip
  - perl-LWP-Protocol-https
  - podman
  - prettyping
  - restic
  - sqlite
  - stow
  - tmux
  - ulauncher
  - util-linux-user
  - variety
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  # - mpv

remove_packages:
  - chrome-gnome-shell
  - chromium
  - flameshot
  - flowblade
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-window-list
  - gtk-murrine-engine
  - gtkhash-nautilus
  - libreoffice-calc
  - libreoffice-core
  - libreoffice-data
  - libreoffice-emailmerge
  - libreoffice-filters
  - libreoffice-graphicfilter
  - libreoffice-gtk3
  - libreoffice-help-en
  - libreoffice-impress
  - libreoffice-langpack-en
  - libreoffice-ogltrans
  - libreoffice-opensymbol-fonts
  - libreoffice-pdfimport
  - libreoffice-pyuno
  - libreoffice-ure
  - libreoffice-ure-common
  - libreoffice-writer
  - libreoffice-x11
  - libreoffice-xsltfilter
  - parallel
  - remmina
  - remmina-plugins-rdp
  - remmina-plugins-spice
  - remmina-plugins-vnc
  - tilix
  - tilix-nautilus
  - tint2
  - totem
  - virtualbox-guest-additions