---
# Themes are in a dir/theme format
# Directories are either Themes or Themes-2

dotfiles_repo_RO: https://github.com/Findarato/dotFiles.git
dotfiles_repo_RW: git@github.com:Findarato/dotFiles.git

install_packages: [
    'htop',
    'wget',
    'curl',
    'python-pip',
    'nano',
    'openssh',
    'fwbackups',
    'tmux',
    'vlc',
    'mpv',
    'fslint',
    'wget',
    'p7zip',
    'seahorse-nautilus',
    'tilix',
    'tilix-nautilus',
    'chromium',
    'chrome-gnome-shell',
    'lm_sensors',
    'gnome-shell-extension-topicons-plus',
    'gnome-shell-extension-calc',
    'gnome-tweak-tool',
    'gtk-murrine-engine',
    'remmina',
    'remmina-plugins-rdp',
    'remmina-plugins-spice',
    'remmina-plugins-vnc',
    'util-linux-user',
    'dnf-plugins-core',
    'sqlite',
    'python3',
    'python3-pip',
    'ImageMagick',
    # 'python-firewall',
    'parallel',
    'brasero',
    'dnf-automatic',
    'jq',
    'yubioath-desktop'
    ]

remove_packages: [
  gnome-shell-extension-background-logo,
  gnome-shell-extension-window-list,
  tint2
]

extra_font_files: 
  - adobe-source-code-pro-fonts
  - dejavu-sans-fonts
  - dejavu-sans-mono-fonts
  - dejavu-serif-fonts
  - gnu-free-fonts-common
  - gnu-free-mono-fonts
  - gnu-free-sans-fonts
  - gnu-free-serif-fonts
  - levien-inconsolata-fonts
  - liberation-fonts-common
  - liberation-mono-fonts
  - liberation-sans-fonts
  - liberation-serif-fonts
  - mozilla-fira-mono-fonts
  - msimonson-anonymouspro-fonts
  - overpass-fonts
  - terminus-fonts
  - google-android-emoji-fonts
  - google-noto-fonts-common
  - google-android-emoji-fonts
...