---
# Setup some gaming specific things

- name: Install Gaming Packages
  dnf:
    state: present
    name: "{{ install_gaming_packages}}"
  when:
    - enable_gaming == true

- name: Install Flatpak -> Discord
  flatpak:
    name: com.discordapp.Discord
    state: present
    remote: flathub
  when:
    - enable_gaming == true
  tags:
    - flatpak
    - packages

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: gaming
  register: gaming_temp

- name: Clone Game Udev rules
  ansible.builtin.git:
    repo: https://gitlab.com/jntesteves/game-devices-udev.git
    dest: "{{ gaming_temp.path }}"

- name: Install gaming Udev rules
  ansible.builtin.copy:
    src: "{{ gaming_temp.path }}/"
    dest: /etc/udev/rules.d/

- name: enable uinput
  ansible.builtin.copy:
    src: uinput.conf
    dest: "/etc/modules-load.d/uinput.conf"
