---
# Setup and install I3-gaps on the computer

# - name: i3 -> i3-gaps Copr
#   yum_repository:
#     name       : nforro-i3-gaps
#     description: Copr repo for i3-gaps owned by nforro
#     baseurl    : "https://copr-be.cloud.fedoraproject.org/results/nforro/i3-gaps/fedora-$releasever-$basearch/"
#     file       : copr_repos
#     gpgcheck   : yes

- name: i3 -> Required Packages
  ansible.builtin.package:
    name: "{{ i3_packages }}"
    state: present
  tags:
    - i3

- name: Get i3 Blocks
  become: false
  git:
    repo: "https://github.com/vivien/i3blocks"
    dest: "{{ scratch_dir }}/i3Blocks"
    accept_hostkey: true
    track_submodules: true
    update: true
  register: result
  ignore_errors: true
  tags:
    - i3
    - git

- name: i3Blocks -> Setup Autogen
  ansible.builtin.shell: "./autogen.sh"
  args:
    chdir: "{{ scratch_dir }}/i3Blocks/"
    creates: "{{ scratch_dir }}/i3Blocks/autom4te.cache/requests"
  tags:
    - i3

- name: i3Blocks -> Configure
  ansible.builtin.shell: "./configure"
  args:
    chdir: "{{ scratch_dir }}/i3Blocks/"
    creates: "{{ scratch_dir }}/i3Blocks/Makefile"
  tags:
    - i3

- name: i3Blocks -> Build
  ansible.builtin.shell: "make"
  args:
    chdir: "{{ scratch_dir }}/i3Blocks/"
    creates: "{{ scratch_dir }}/i3Blocks/i3blocks"
  tags:
    - i3

- name: i3Blocks -> Install
  ansible.builtin.shell: "make install"
  args:
    chdir: "{{ scratch_dir }}/i3Blocks/"
    creates: "/usr/local/bin/i3blocks"
  tags:
    - i3
