
# - name: Running OS specific Configurations and Commands
#   include: "{{item}}"
#   with_items:
#   - "{{ ansible_os_family }}/repos.yml"
#   - "{{ ansible_os_family }}/system.yml"
#   - "{{ ansible_os_family }}/packages.yml"

#- name: Running generic Configurations and Commands
#  include: "{{item}}"
#  with_items:
  #- "all_system.yml"
  #- font.yml
  #- base16.yml
