---

- name: Running OS specific Configurations and Commands
  include: "{{item}}"
  with_items:
  - "{{ ansible_os_family }}_system.yml"
  - "{{ ansible_os_family }}_packages.yml"


#- name: Running generic Configurations and Commands
#  include: "{{item}}"
#  with_items:
  #- "all_system.yml"
  #- font.yml
  #- base16.yml


- name: Upgrade PIP
  pip: name=pip state=latest

- name: Installing python kerberos
  pip: name=kerberos state=latest

- name: Installing required libraries for Windows connections
  pip: name=pywinrm state=latest


# Follow this guide locally, it is going to be a bitch to setup.
# I will eventually fix it

# http://docs.ansible.com/ansible/intro_windows.html

# Referencing the page I used to find out most of this https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html
