---
- name:             Ensure .ssh directory exists.
  file:
    dest:           "/home/{{myuser}}/.ssh/"
    mode:           0700
    owner:          "{{myuser}}"
    state:          directory

- name:             Ensure Tilix config directory exsists
  file:
    dest:           "/home/{{myuser}}/.config/tilix/schemes/"
    mode:           0700
    owner:          "{{myuser}}"
    state:          directory

- name:             Add Private Keys
  copy:
    content:        "{{ item.key }}"
    dest:           "/home/{{myuser}}/{{item.name}}"
    backup:           yes
  with_items:       "{{ private_keys }}"


- name:             Create src folder
  file:
    path:           "/home/{{myuser}}/Documents/src/"
    state:          directory
    mode:           0750

- name:             Clone dotfiles repos
  become:      false
  git:
    repo:           git@github.com:Findarato/dotFiles.git
    dest:           "/home/{{myuser}}/Documents/src/dotFiles"
    # version:      release-1
    key_file:       "/home/{{myuser}}/.ssh/github"
    accept_hostkey: yes
    track_submodules: yes
    update: yes
    force: yes

- name: Link up Home directory to dotfiles
  become:      false
  file:
    src: '/home/{{myuser}}/Documents/src/dotFiles/{{ link_file }}'
    dest: '/home/{{myuser}}/{{ link_file }}'
    state: link
  with_items:
    - bin
    - .aliases
    - .ansible.cfg
    - .bashrc
    - .dircolors
    - .functions
    - .gitconfig
    - .gitignore
    - .gitmessage
    - .gitmodules
    - .powerlevel9k
    - .rainbow_config.json
    - .zprofile
    - .zshrc
  loop_control:
    loop_var: link_file



- name:             Copy Tilix Themes
  copy:
    src:            "/home/{{myuser}}/Documents/src/dotFiles/Tilix-Themes/{{ item }}"
    dest:           "/home/{{ myuser }}/.config/tilix/schemes/"
    backup:         yes
  with_items:       
    - "{{ tilix_themes }}"


# - name: Install Tilix Themes 1
#   synchronize:
#     src: '/home/{{myuser}}/Documents/src/dotFiles/Tilix-Themes/Themes/'
#     dest: "/home/{{ myuser }}/.config/tilix/schemes/"



# - name: Install Tilix Themes 2
#   synchronize:
#     src: '/home/{{myuser}}/Documents/src/dotFiles/Tilix-Themes/Themes-2/'
#     dest: "/home/{{ myuser }}/.config/tilix/schemes/"

- name:           Running OS specific Configurations and Commands
  include:        "{{include_file}}"
  with_items:
  - "{{ ansible_distribution }}/repos.yml"
  - "{{ ansible_distribution }}/system.yml"
  - "{{ ansible_distribution }}/packages.yml"
  loop_control:
    loop_var: include_file