
# - name: Running OS specific Configurations and Commands
#   include: "{{item}}"
#   with_items:
#   - "{{ ansible_os_family }}/repos.yml"
#   - "{{ ansible_os_family }}/system.yml"
#   - "{{ ansible_os_family }}/packages.yml"

#- name: Running generic Configurations and Commands
#  include: "{{item}}"
#  with_items:
  #- "all_system.yml"
  #- font.yml
  #- base16.yml


# - file:
#     src: /file/to/link/to
#     dest: /path/to/symlink
#     owner: foo
#     group: foo
#     state: link


- name: Create src folder
  file:
    path: "/home/{{myuser}}/Documents/src/"
    state: directory
    mode: 0750

- name: Clone dotfiles repos
  git:
    repo: git@github.com:Findarato/dotFiles.git
    dest: "/home/{{myuser}}/Documents/src/dotFiles"
    # version: release-1
    key_file: "{{ lookup('file', '/home/joe/.ssh/github.pub') }}"
    # key_file: "{{ github_keyfile }}"
    accept_hostkey: yes


# - file:
#     src: /file/to/link/to
#     dest: /path/to/symlink
#     owner: foo
#     group: foo
#     state: link
