---

# - name:               Ensure .ssh directory exists.
#   file:
#     dest:             "/home/{{ local_user }}/.ssh/"
#     mode:             0700
#     owner:            "{{ local_user }}"
#     state:            directory

# - name:               Add Private Keys
#   copy:
#     content:          "{{ item.key }}"
#     dest:             "/home/{{ local_user }}/.ssh/{{ item.name }}"
#     backup:           yes
#   with_items:         "{{ private_keys }}"
#   no_log: true

- name:               Ensure Tilix config directory exsists
  file:
    dest:             "/home/{{ local_user }}/.config/tilix/schemes/"
    mode:             0700
    owner:            "{{ local_user }}"
    state:            directory

- name:               Generate Private keys
  user:
    name:             "{{ local_user }}"
    generate_ssh_key: true
  no_log: true

- name:               Create src folder
  file:
    path:             "/home/{{ local_user }}/Documents/src/"
    state:            directory
    owner:            "{{ local_user }}"
    mode:             0750

- name:               Clone dotfiles repos
  become:             false
  git:
    repo:             "{{ dotfiles_repo_RW }}"
    dest:             "/home/{{ local_user }}/dotFiles"
    key_file:         "/home/{{ local_user }}/.ssh/github"
    accept_hostkey:   yes
    track_submodules: yes
    update:           yes
    # version:          v1.7
  register:           result
  ignore_errors:      yes
  tags:
    - git
    - dotfiles

# - name:               Delete exsisting files in home directory
#   become:             false
#   file:
#     dest:             "/home/{{ local_user }}/{{ old_file }}"
#     state:            absent
#   with_items:
#     - .aliases
#     - .ansible.cfg
#     - .bashrc
#     - .dircolors
#     - .functions
#     - .gitconfig
#     - .gitignore
#     - .gitmessage
#     - .gitmodules
#     - .powerlevel9k
#     - .rainbow_config.json
#     - .zprofile
#     - .zshrc
#     - bin
#   loop_control:
#     loop_var:         old_file
#   when:               result is changed
#   tags:
#     - git
#     - dotfiles

# - name:               Link up Home directory to dotfiles
#   become:             false
#   file:
#     src:              "/home/{{ local_user }}/Documents/src/dotFiles/{{ link_file }}"
#     dest:             "/home/{{ local_user }}/{{ link_file }}"
#     state:            link
#   with_items:
#     - .aliases
#     - .ansible.cfg
#     - .bashrc
#     - .dircolors
#     - .functions
#     - .gitconfig
#     - .gitignore
#     - .gitmessage
#     - .gitmodules
#     - .powerlevel9k
#     - .rainbow_config.json
#     - .zprofile
#     - .zshrc
#     - bin
#   loop_control:
#     loop_var:         link_file
#   when:               result is changed
#   tags:
#     - git
#     - dotfiles

- name:               Copy Tilix Themes
  copy:
    src:              "/home/{{ local_user }}/dotFiles/Tilix-Themes/{{ item }}"
    dest:             "/home/{{ local_user }}/.config/tilix/schemes/"
  with_items:
    - "{{ tilix_themes }}"
  when:               result is changed

- name:               Running OS specific Configurations and Commands
  include_tasks:            "{{ include_file }}"
  with_items:
    # - "{{ ansible_distribution }}/repos.yml"
    - "{{ ansible_distribution }}/system.yml"
    - "{{ ansible_distribution }}/packages.yml"
    # - "{{ ansible_distribution }}/services.yml"
    # - "{{ ansible_distribution }}/configuration.yml"
    # - "{{ ansible_distribution }}/flatpak.yml"
  loop_control:
    loop_var:         include_file
  tags:
    - configuration

- name: Configure the system
  include_tasks: "{{ ansible_distribution }}/configuration.yml"
  tags:
    - dconf
    - install
    - configuration

- name: Setup and install Flatpak
  include_tasks: "{{ ansible_distribution }}/flatpak.yml"
  tags:
    - flatpak
    - install
    - configuration

- name: Setup Ram CACHE fstab
  mount:
    path: /mnt/cache
    src: tmpfs
    fstype: tmpfs
    state: present
    opts: nodev,nosuid,noexec,nodiratime,size=512M
  when:
    - ram_cache == true

...