---
#Remove Packages
- name: Remove Packages
  ansible.builtin.dnf:
    state: absent
    name: "{{ remove_packages }}"

# Install Packages
- name: Install Packages
  ansible.builtin.dnf:
    state: present
    name: "{{ install_packages }}"
  #Keyboard Config. This will eventually be its own role.

- name: Upgrade PIP
  ansible.builtin.pip:
    name: pip
    state: latest
    extra_args: --user

- name: Install Required Python libraries
  become: false
  ansible.builtin.pip:
    name: "{{ python_packages }}"
    state: latest
    extra_args: --user --upgrade

- name: Install Extra Font Packages
  ansible.builtin.dnf:
    name: "{{ extra_font_files }}"
    state: present
  when: install_extra_fonts
  notify: Update Font Cache

- name: Install CIFS Utils
  ansible.builtin.dnf:
    name: cifs-utils
    state: present
  when:
    - work_computer == true

- name: Install CIFS Utils
  ansible.builtin.dnf:
    name: cifs-utils
    state: present
  when:
    - work_computer == true

- name: Install Bibata Cursors
  ansible.builtin.dnf:
    name: bibata-cursor-themes
    state: present
  ignore_errors: true