---
# Remove Files
- name: Remove unneeded packages
  dnf: state=absent purge=yes name={{item}}
  with_items:
    - dell-super-key
    - thunderbird

# Install Files
- name: Install needed packages
  dnf: state=present name={{item}}
  with_items:

   # Screensavers
    - xscreensaver-gl
    - xscreensaver-gl-extra
    - xscreensaver-screensaver-dizzy
    - xscreensaver-screensaver-webcollage
    - xscreensaver-data-extra
    - rss-glx-xscreensaver
    - rss-glx
    # Core Desktop Tools
    - htop
    - wget
    - curl
    - nano
    - python-pycurl
    - phoronix-test-suite
    - firefox
    - python-pip
    - qt4-dev-tools
    - build-essential
    - libx11-6
    - libx11-dev
    - libx11-guitest-perl
    - evolution
    - python-devel
    - krb5-devel
    - krb5-libs
    - krb5-workstation
    - yum-plugin-fastestmirror
    - nano
	  - levien-inconsolata-fonts
    - adobe-source-code-pro-fonts
	  - mozilla-fira-mono-fonts
    - google-droid-sans-mono-fonts
	  - openssh
    - filezilla
    - python
    - xclip
    - inotify-tools
	  - npm
    - which
    - make
    - vagrant
    -  xbindkeys
     - xautomation
	    - solaar
      - parallel
      - vlc screenfetch
      - fslint
	    - wget
      - p7zip
      - expect
