---
# - debug:
#     msg:    "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Install 3rd Party Repos
  ansible.builtin.package:
    state: present
    name: fedora-workstation-repositories

- name: Install RPM Fusion "Free"
  ansible.builtin.package:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

- name: Install RPM Fusion "nonFree"
  ansible.builtin.package:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

- name: Enable bibata-cursor-themes CPOR
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: peterwu/rendezvous
