---
# - debug:
#     msg:    "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"


- name:     Install 3rd Party Repos
  package:
    state: present
    name: fedora-workstation-repositories

- name:     Download Enpass Repo
  get_url:
    url:    "https://yum.enpass.io/enpass-yum.repo"
    mode:   0644
    dest:   "/etc/yum.repos.d/enpass-yum.repo"
  when:
    - install_enpass == true